# 使用 Python 3.8 官方镜像作为基础镜像
FROM python:3.8

# 设置工作目录
WORKDIR /src

# 使用阿里云的 Python 包镜像源来加速包下载
RUN pip install --index-url http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com --default-timeout=2000\
    tensorflow==2.3.0 --no-cache-dir \
    numpy==1.18.5 \
    scikit-learn==1.2.2 \
    scipy==1.4.1 \
    matplotlib==3.3.4 \
    pandas==1.1.5 \
    joblib==1.3.2 \
    protobuf==3.20.0 \
    sequential==1.0.0\
    pillow==10.2.0

COPY . /src

# 运行应用程序
CMD ["python", "main.py"]
